
<div class="row">
    <div class=" col-lg-1"></div>
    <div class=" col-lg-10">
	<div class="panel">
	    <div class="panel-heading">
		<div class="panel-title">
		    <h3><i class="glyphicon glyphicon-plus"></i> <?php echo 'cliente'; ?></h3>
		</div>
	    </div>
	    <div class="panel-body">

		<h3>Adicionar Cliente</h3>
		<?php echo $this->form()->openTag($form); ?>
		<?php echo $this->formCollection($form); ?>
		<input type="submit" value="Salvar" class="btn btn-sm btn-primary" />
		<?php echo $this->form()->closeTag($form); ?>

		<div class="panel-footer">

		</div>
	    </div>
	</div>
    </div>
    <div class=" col-lg-1"></div>
</div>

