<div class="row">
    <div class="col-lg-12">
	<div class="panel">
	    <div class="panel-heading">
		<div class="panel-title col-lg-12">
		    <i class="glyphicons glyphicons-cart_in"></i> <h1>Carrinho de Compras</h1>
		</div>
	    </div>
	    <div class="panel-menu" style="height: 50px">
		<div class="col-lg-8">
		    <a href="<?php echo $this->url('cart/destroy') ?>" class="btn btn-blue btn-gradient"><i class="fa fa-trash"></i> Limpar Carrinho</a>
		    <a href="<?php echo $this->url('cart/add') ?>" class="btn btn-blue btn-gradient"><i class="fa fa-cart-plus"></i> Add Carrinho</a>
		</div>
		<div class="col-lg-4"></div>
	    </div>
	    <div class="panel-body">

		<?php if ($total_items > 0): ?>
    		<h3><?php echo $this->translate('Products in cart') ?> (<?php echo $total_items; ?>):</h3>
    		<table class="table">
    		    <thead>
    			<tr>
    			    <th>Id</th>
    			    <th>Qty</th>
    			    <th>Name</th>
    			    <th>Item Price</th>
    			    <th>Sub-Total</th>
    			</tr>
    		    </thead>
    		    <tbody>
			    <?php foreach ($items as $key): ?>
				<tr>
				    <td style="text-align: center;"><?php echo $key['id']; ?></td>
				    <td style="text-align: center;"><?php echo $key['qty']; ?></td>
				    <td style="text-align: center;">
					<?php echo $key['name']; ?>
					<?php if ($key['options'] != 0): ?>
	    				Options:
					    <?php foreach ($key['options'] as $options => $value): ?>
						<?php echo $options . ' ' . $value; ?>
					    <?php endforeach; ?>
					<?php endif; ?>
				    </td>
				    <td style="text-align: center;"><?php echo $key['price']; ?></td>
				    <td style="text-align: center;"><?php echo $key['sub_total']; ?></td>
				</tr>
			    <?php endforeach; ?>
    			<tr>
    			    <td colspan="2"></td>
    			    <td style="text-align: center;"><strong>Sub Total</strong></td>
    			    <td style="text-align: center;"> <?php echo $total['sub-total']; ?></td>
    			</tr>
    			<tr>
    			    <td colspan="2"></td>
    			    <td style="text-align: center;"><strong>Vat</strong></td>
    			    <td style="text-align: center;"> <?php echo $total['vat']; ?></td>
    			</tr>
    			<tr>
    			    <td colspan="2"></td>
    			    <td style="text-align: center;"><strong>Total</strong></td>
    			    <td style="text-align: center;"> <?php echo $total['total']; ?></td>
    			</tr>
    		    </tbody>
    		</table>

		<?php else: ?>
    		<h4>The Shopping Cart Empty</h4>
		<?php endif; ?>

	    </div>
	    <div class="panel-footer">
		<div class="col-lg-12">

		</div>
	    </div>
	</div>
    </div>
</div>
</div>
</div>