
<div class="row">
    <div class=" col-lg-1"></div>
    <div class=" col-lg-10">
	<div class="panel">
	    <div class="panel-heading">
		<div class="panel-title">
		    <h3><i class="glyphicon glyphicon-edit"></i> <?php echo 'produto'; ?></h3>
		</div>
	    </div>
	    <div class="panel-body">
		<?php
		echo $this->acploForm($this->entityForm);
		?>
		<div class="panel-footer">
		</div>
	    </div>
	</div>
    </div>
    <div class=" col-lg-1"></div>
</div>


